//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp81.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stgAllowWritesToRom {
            get {
                return ((bool)(this["stgAllowWritesToRom"]));
            }
            set {
                this["stgAllowWritesToRom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color stgBackColour {
            get {
                return ((global::System.Drawing.Color)(this["stgBackColour"]));
            }
            set {
                this["stgBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color stgBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["stgBorderColour"]));
            }
            set {
                this["stgBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int stgDisplaySize {
            get {
                return ((int)(this["stgDisplaySize"]));
            }
            set {
                this["stgDisplaySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color stgFastModeColour {
            get {
                return ((global::System.Drawing.Color)(this["stgFastModeColour"]));
            }
            set {
                this["stgFastModeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color stgForeColour {
            get {
                return ((global::System.Drawing.Color)(this["stgForeColour"]));
            }
            set {
                this["stgForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stgHideTB {
            get {
                return ((bool)(this["stgHideTB"]));
            }
            set {
                this["stgHideTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stgTapeDir {
            get {
                return ((string)(this["stgTapeDir"]));
            }
            set {
                this["stgTapeDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stgHideScreenInFastMode {
            get {
                return ((bool)(this["stgHideScreenInFastMode"]));
            }
            set {
                this["stgHideScreenInFastMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("416, 449")]
        public global::System.Drawing.Size stgFormSize {
            get {
                return ((global::System.Drawing.Size)(this["stgFormSize"]));
            }
            set {
                this["stgFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection stgMacros {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stgMacros"]));
            }
            set {
                this["stgMacros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection stgMacroDescriptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stgMacroDescriptions"]));
            }
            set {
                this["stgMacroDescriptions"] = value;
            }
        }
    }
}
